<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{8ae3b7d7-24a5-400d-acc1-48a87b859bdb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Zusstandsautomaten	: ControlZustandsautomat;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Zusstandsautomaten();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>